server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(zi7f8wPOxsreXUXM8eC9c01rrmoObqPrSyJVsPXrmBfRDT37vzumClc7rASJ9AP7zZiI6/NJy+DGwkkVRpgj81ritwqs9lW60H8n3uZxc+B5M5OWjy73Gj0qiceco9a4mcpN6ToIibI=)
    username: ENC(XvZG9opo+YPiXK1bz4mgLw==)
    password: ENC(iT+geuj4qh+tvJEs91afp2oxqm/s+7O6)
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: master2011
  mail:
    host: smtp.qq.com
    username: 1498097245@qq.com
    password: sputxexvxrgoihef
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/files/
  thymeleaf:
    enabled: true
    check-template: true
    suffix: .html
    prefix: classpath:/templates/
  # 返回的api接口的配置，全局有效
  #jackson:
  #default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段

#jasypt加密的密匙
#jasypt:
#  encryptor:
#    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7


mail:
  fromMail:
    addr: alex9012@qq.com

# 日志级别
logging:
  level:
    root: info
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace

## 开启定时任务
scheduling:
  enabled: false

user:
  export: "F://project//spring-boot-api-scaffold//src/main//resources//files//"
  mac-export: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/files/"
